name: AntiSpam
main: AntiSpam\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

permissions:
  antispam.bypass:
    description: Bypass chat cooldown and spam checks
    default: op

  antispam.caplock:
    description: Bypass caps protection
    default: op

  antispam.see:
    description: Receive AntiSpam staff alerts
    default: op
